### ISSUE TITLE
Resource not found - retry?

### ISSUE THREAD

**Issue by ianjuma** [ianjuma/pubmed#1]
log and retry?

```python
Article ID:  25701866
ISSN No:  1537-6613
Date published: 2015-02-20
Traceback (most recent call last):
  File "scrap_pubmed.py", line 70, in <module>
    data_frame = fetch_page_per_index(paper['MedlineCitation']['Article']['ArticleTitle'])
  File "/home/synod/AT/scrap/pub_med.py", line 11, in fetch_page_per_index
    page = urllib2.urlopen(skeletal_url % index)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

bio python lib fails to gracefully shut down or retry.

**Comment by ianjuma** [comment]
handled exceptions and fixed issue
